name: Publish to Maven Central
on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.SIGNING_KEY }}
          passphrase: ${{ secrets.SIGNING_PASSWORD }}
      - name: Show generated settings.xml
        run: |
          echo "=== ~/.m2/settings.xml ==="
          cat ~/.m2/settings.xml

      - name: Publish with debug
        run: |
          chmod +x expand.sh
          ./expand.sh ~/.m2/settings.xml > ~/.m2/settings-resolved.xml
          mv ~/.m2/settings-resolved.xml ~/.m2/settings.xml

          ./gradlew publish --no-daemon --info \
            -PreleaseVersion="${{ github.event.release.tag_name }}" \
            -PsigningKey="${{ secrets.SIGNING_KEY }}" \
            -PsigningPassword="${{ secrets.SIGNING_PASSWORD }}"
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_TOKEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN_PASSWORD }}
