name: Publish to Maven Central
on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # fetch code & tags :contentReference[oaicite:21]{index=21}
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17" # or your target JDK :contentReference[oaicite:22]{index=22}
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5 # load private key into runner :contentReference[oaicite:23]{index=23}
        with:
          gpg_private_key: ${{ secrets.SIGNING_KEY }}
          passphrase: ${{ secrets.SIGNING_PASSWORD }}
      - name: Publish artifacts
        run: |
          ./gradlew publish \
            --no-daemon \
            -PreleaseVersion="${{ github.event.release.tag_name }}" \
            -PossrhUsername="${{ secrets.OSSRH_USERNAME }}" \
            -PossrhPassword="${{ secrets.OSSRH_PASSWORD }}" \
            -PsigningKey="${{ secrets.SIGNING_KEY }}" \
            -PsigningPassword="${{ secrets.SIGNING_PASSWORD }}"
